meetme_login:
    path:     /login
    defaults: { _controller: autostopBundle:login:login }

meetme_signup:
    path:     /registro
    defaults: { _controller: autostopBundle:signup:signup }

meetme_profile:
    path:     /profile/{usuariop}
    defaults: { _controller: autostopBundle:profile:profile }
    
meetme_reload:
    path:     /inicio
    defaults: { _controller: autostopBundle:login:reload }  

meetme_logout:
    path:     /logout
    defaults: { _controller: autostopBundle:logout:logout }
    
meetme_informalevent:
     pattern:     /eventoinformal
     defaults: { _controller: autostopBundle:informalEvent:informalEvent }
     
meetme_formalevent:
     pattern:     /eventoformal
     defaults: { _controller: autostopBundle:formalEvent:formalEvent }
     
daw_autostop_notificacion:
    path:     /notificacion/{idruta}/{idEstudiante}
    defaults: { _controller: autostopBundle:notificacion:enviarNotificaciones }
    
daw_autostop_nueva_ruta:
    path:     /nuevaruta
    defaults: { _controller: autostopBundle:nuevaRuta:nuevaruta }
    options:
        expose: true
           
meetme_friends:
    pattern:  /{usuariop}
    defaults: { _controller: autostopBundle:friends:add }
    options:
        expose: true
        
daw_autostop_puntos:
    path:     /puntos
    defaults: { _controller: autostopBundle:nuevaRuta:puntos }
    options:
        expose: true
        
daw_autostop_buscar:
    pattern: /
    defaults: { _controller: autostopBundle:nuevaRuta:buscar }
    options:
        expose: true
        
meetme_friendsd:
    pattern:  /p/{usuariop}
    defaults: { _controller: autostopBundle:friends:delete }
    options:
        expose: true



    