services:
    acme_hello.topic_sample_service:
        class: autostopBundle\Topic\AcmeTopic
        tags:
            - { name: gos_web_socket.topic }

    acme_hello.rpc_sample_service:
        class: autostopBundle\Rpc\AcmeRpc
        tags:
            - { name: gos_web_socket.rpc }
            
#    autostop.example:
#        class: autostopBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
