meetme_index:
    path:     /index
    defaults: { _controller: meetmeBundle:nologin:nologin }  
    
meetme_login:
    path:     /login
    defaults: { _controller: meetmeBundle:login:login }
    
meetme_email:
    path:     /email
    defaults: { _controller: meetmeBundle:email:email }
    
meetme_signup:
    path:     /signup
    defaults: { _controller: meetmeBundle:signup:signup }
    
meetme_signupfail:
    path:     /signupfail
    defaults: { _controller: meetmeBundle:signupfail:signupfail }
   
meetme_upload:
    path:     /upload
    defaults: { _controller: meetmeBundle:upload:upload }
    
meetme_upload_success:
    path:     /upload_success
    defaults: { _controller: meetmeBundle:upload:uploadsuccess }    
    
meetme_profile:
    path:     /profile/{usuariop}
    defaults: { _controller: meetmeBundle:profile:profile }
    
meetme_reload:
    path:     /index/1
    defaults: { _controller: meetmeBundle:login:reload }  
    
meetme_logout:
    path:     /logout
    defaults: { _controller: meetmeBundle:logout:logout }
    
meetme_informalevent:
     pattern:     /informalevent
     defaults: { _controller: meetmeBundle:informalEvent:informalEvent }
     
meetme_formalevent:
     pattern:     /formalevent
     defaults: { _controller: meetmeBundle:formalEvent:formalEvent }
     
meetme_createdevent:
     pattern:     /createdevent
     defaults: { _controller: meetmeBundle:createdEvent:createdEvent }
     
meetme_searchevent:
     pattern:     /searchevent
     defaults: { _controller: meetmeBundle:searchEvent:searchEvent }
     
meetme_forgotpassword:
    path:     /forgotpassword
    defaults: { _controller: meetmeBundle:forgotPassword:forgotPassword }
    
meetme_forgot_pass_email:
    path:     /emailforgotpass
    defaults: { _controller: meetmeBundle:emailForgotPass:emailForgotPass }
     
meetme_image:
    resource: "@meetmeBundle/Resources/config/routing/image.yml"
    prefix:   /admin/image
    
meetme_country:
    resource: "@meetmeBundle/Resources/config/routing/country.yml"
    prefix:   /admin/country

meetme_user:
    resource: "@meetmeBundle/Resources/config/routing/user.yml"
    prefix:   /admin/user